# Generated by Django 2.2.2 on 2019-06-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeid', models.CharField(max_length=10)),
                ('storename', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('last_modify_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
