# Generated by Django 2.2.2 on 2019-06-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tppbot', '0002_auto_20190628_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='create_date',
            field=models.DateTimeField(verbose_name='date create'),
        ),
        migrations.AlterField(
            model_name='store',
            name='last_modify_date',
            field=models.DateTimeField(verbose_name='date modify'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(verbose_name='date join'),
        ),
    ]
